version: "3.0"
networks:
    main:
        external: true
services:
  api:
    container_name: mailer_api
    restart: always
    networks:
      - main
    build:
      context: ./api/
      dockerfile: ./Dockerfile
    command: bash -c "npm install && node ."
    volumes:
      - ./api:/usr/src/app
    ports:
      - "81:3000"
    environment:
      KAFKA_URL: kafka:29092
  mongo:
    container_name: mailer_mongo
    image: mongo:latest
    networks:
      - main
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
  # dkron:
  #   container_name: dkron
  #   image: dkron/dkron:latest
  #   command: agent --server
  #   ports:
  #     - 8080:8080
  #   volumes:
  #     - ./data/dkron.db:/dkron.db